# ============================================================================
# PRISM PLATFORM - Docker Compose Configuration
# ============================================================================

version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:8.0
    container_name: prism-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: prismAdmin
      MONGO_INITDB_ROOT_PASSWORD: prismDev2025
      MONGO_INITDB_DATABASE: prism
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - prism-network

  # Redis (Optional - for caching)
  redis:
    image: redis:7-alpine
    container_name: prism-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - prism-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  prism-network:
    driver: bridge
